# Generated by Django 2.2.3 on 2019-07-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moive',
            name='Release_time',
            field=models.IntegerField(verbose_name='上映天数'),
        ),
        migrations.AlterField(
            model_name='moive',
            name='row_screenings',
            field=models.IntegerField(verbose_name='实时场次'),
        ),
    ]
