# Generated by Django 2.2.3 on 2019-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moive', '0002_auto_20190730_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moive',
            name='precent',
            field=models.CharField(max_length=6, verbose_name='实时排片'),
        ),
    ]
