# Generated by Django 2.2.3 on 2019-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moive', '0003_auto_20190730_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moive',
            name='real_time_gross',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=12, verbose_name='实时票房'),
        ),
        migrations.AlterField(
            model_name='moive',
            name='total_box_office',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=12, verbose_name='累计票房'),
        ),
    ]
