# Generated by Django 2.2.3 on 2019-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moive', '0004_auto_20190730_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moive',
            name='id',
        ),
        migrations.AlterField(
            model_name='moive',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='电影名称'),
        ),
    ]
